### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by yx568481693** [CryptoExperts/Tornado#1]
hi
I used the case, 
./tornado -B -light-inline -tp -ua-masked -o ace_bitslice.c usuba/samples/usuba/ace.ua
but an error occurred

warning : "RC_[2][15][30] = setcstall(0x0)" is not a comment or a valid expression. (line 3076)
warning : "RC_[2][15][31] = setcstall(0x1)" is not a comment or a valid expression. (line 3077)
Traceback (most recent call last):
  File "/home/eval/tornado/tightPROVEp/tightprove-exec.sage.py", line 76, in <module>
    find_refresh_v1(filename_in,savef=False,verbose=False,save=_sage_const_1 ,saveto=filename_out,showgraph=False)
  File "<string>", line 158, in find_refresh_v1
  File "<string>", line 442, in format_code
KeyError: 'RC_[0][0][31]'
Fatal error: exception Sys_error("/home/eval/tornado/usuba/tightprove_cache/226074392/refreshed.tp: No such file or directory")
Raised by primitive operation at file "stdlib.ml", line 398, characters 28-54

How can i solve it
thanks

**Comment by DadaIsCrazy** [comment]
Hi,
Thank you for reporting this issue.
I've updated the Usuba version used in Tornado, which should have fixed the issue (it did on my tests at least).
Let us know if you still have some troubles using Tornado! :)

Regards,
Darius
