### ISSUE TITLE
Implementation on Microcontroller

### ISSUE THREAD

**Issue by NGSecure** [CryptoExperts/Tornado#3]
Hi, Professor:
Could you provide command instruction on how to run the code on microcontroller Arm Cortex-M4 which was used in your paper?
Thank you.

**Comment by DadaIsCrazy** [comment]
Hi,

The code used to run the benchmarks is in this repository: https://github.com/pedagand/usuba-nucleo

You should run `make clone-usuba` to retrieve the C source codes of the ciphers. Then `make all` will run the benchmarks and produce the results in `results/*.dat`. Have a look at the [Makefile](https://github.com/pedagand/usuba-nucleo/blob/master/Makefile) to see how everything works.

Let me know if you need further assistance.

**Comment by NGSecure** [comment]
Hi, professor:

Thank you so much for the help.

I got 2 more questions:

Does the code run on the real device which is Cortex M4 STM32F401RE ?

Did you use any emulator environment to run the code without purchasing the device?

The reason I asked the questions is that I got following errors after copy the maked usuba folder to the directory and run make all command.

adapter speed: 2000 kHz

adapter_nsrst_delay: 100

none separate

srst_only separate srst_nogate srst_open_drain connect_deassert_srst

Info : Unable to match requested speed 2000 kHz, using 1800 kHz

Info : Unable to match requested speed 2000 kHz, using 1800 kHz

Info : clock speed 1800 kHz

Error: open failed

in procedure 'init'

in procedure 'ocd_bouncer'


-From Yunjie

**Comment by DadaIsCrazy** [comment]
Hi,

We did run the code on a real Cortex M4 STM32F401RE.

Here is for instance the output of running the benchmark for Pyjamask vslice masked at order 8 (assuming is has already been compiled, ie, you ran for instance `make usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.elf`):

```
$ make results/bench_masked_8_pyjamask_vslice.dat
objcopy -Oihex usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.elf usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.hex
sudo openocd -f /usr/share/openocd/scripts/board/st_nucleo_f4.cfg \
                -c "init; reset halt; flash write_image erase usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.hex; reset run; exit"
Open On-Chip Debugger 0.9.0 (2018-01-24-01:05)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v23 API v2 SWIM v9 VID 0x0483 PID 0x374B
Info : using stlink api v2
Info : Target voltage: 3.269428
Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints
target state: halted
target halted due to debug-request, current mode: Thread 
xPSR: 0x01000000 pc: 0x0800823c msp: 0x20018000
auto erase enabled
Info : device id = 0x10006433
Info : flash size = 512kbytes
Info : Padding image section 0 with 4 bytes
wrote 65536 bytes from file usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.hex in 3.254906s (19.663 KiB/s)
./bin/serial.sh usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.log
cp usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.log results/bench_masked_8_pyjamask_vslice.dat
rm usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.elf usuba/nist/pyjamask/usuba/bench/masked_8_pyjamask_ua_vslice.hex

$ cat results/bench_masked_8_pyjamask_vslice.dat
^@run; cycles; c/B
0; 124847; 7802;
1; 124826; 7801;
2; 124826; 7801;

```

Warning: you may need to first run `make screen` (and then exit it with `C-a \`), otherwise the output of the benchmark might not be read properly.

As you can see, the beginning of the output you're getting seems normal ("unable to match requested speed 2000 kHz" for instance). I have no idea why the current procedure works on my device but not on yours... Still, Google suggests some fixes when searching for "openocd open failed in procedure 'init' in procedure 'ocd_bouncer'"; maybe some of those can help?

If it can help, I'm using `openocd` 0.9.0.

Let me know if you manage to successfully run the code: maybe I could add some details to the github repository explaining how to fix the issue that you're having :-)

Darius

**Comment by NGSecure** [comment]
Hi, Professor:


I guess I figured out the reason. Comparing your log from the terminal with our ones, the log stopped at Info : STLINK v2 JTAG v23 API v2 SWIM v9 VID 0x0483 PID 0x374B. The reason I guess is that we don’t have the real device connecting to the running PC.



Thank you.



-From Yunjie

**Comment by DadaIsCrazy** [comment]
Alright, I'll close the issue then :)

Thanks for your interest in Tornado!

**Comment by NGSecure** [comment]
Hi, Professor:

I just got the device and tried to run it, then the files in the result folder all show “@^@^@^@^@^…” which are not readable. Could you check this problem?

According to your last email, You mentioned  “Warning: you may need to first run make screen (and then exit it with C-a \), otherwise the output of the benchmark might not be read properly”, but how to do this and I did not find that “make screen” is a command.

Thank you for your time.
-From Yunjie


From: Yunjie Yi <yunjie.yi@uwaterloo.ca>
Date: Tuesday, July 14, 2020 at 4:16 PM
To: CryptoExperts/Tornado <reply@reply.github.com>, CryptoExperts/Tornado <Tornado@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: Re: [CryptoExperts/Tornado] Implementation on Microcontroller (#3)

Hi, Professor:


I guess I figured out the reason. Comparing your log from the terminal with our ones, the log stopped at Info : STLINK v2 JTAG v23 API v2 SWIM v9 VID 0x0483 PID 0x374B. The reason I guess is that we don’t have the real device connecting to the running PC.



Thank you.



-From Yunjie

**Comment by DadaIsCrazy** [comment]
Hi Yunjie,

I meant [`make read`](https://github.com/pedagand/usuba-nucleo/blob/master/Makefile#L158), not `make screen`, sorry.

Or, alternatively, just run `sudo screen /dev/ttyACM0 9600,cs7,ixoff`.

This should fix your issue (_ie_ remove the "@^@^@^@^@^@^...").

Regards,
Darius

**Comment by NGSecure** [comment]
Hi, Prof.:

It works well, thanks for the help.

-From Yunjie
